version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: forrest
      POSTGRES_PASSWORD: forrest
      POSTGRES_DB: superapp
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
